#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e

# 1. Validate that both required arguments are provided
if [ $# -lt 2 ]; then
    echo "❌ Error: Missing required arguments."
    echo "Usage: $0 <CONTAINER_NAME> <BUCKET_TARGET>"
    exit 1
fi

CONTAINER_NAME="$1"
BUCKET_TARGET="$2"

# 2. Generate secure random S3-compatible credentials
# Access Key: 20 characters uppercase alphanumeric
APP_ACCESS_KEY=$(head /dev/urandom | tr -dc 'A-Z0-9' | head -c 20)
# Secret Key: 40 characters alphanumeric + basic safe symbols
APP_SECRET_KEY=$(head /dev/urandom | tr -dc 'A-Za-z0-9+/=' | head -c 40)

echo "🔄 Initialising restricted credentials configuration..."
echo "📍 Target Container : $CONTAINER_NAME"
echo "📍 Target Bucket    : $BUCKET_TARGET"

# 3. Pass the script payload into the container shell via standard input
docker exec -i "$CONTAINER_NAME" /bin/sh << EOF
set -e

# Setup the CLI client alias using internal container environment variables
mc alias set myminio http://localhost:9000 \$MINIO_ROOT_USER \$MINIO_ROOT_PASSWORD

# Write out the scoped read/write policy configuration file locally
cat <<POLICY_EOF > /tmp/${BUCKET_TARGET}-policy.json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::${BUCKET_TARGET}"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::${BUCKET_TARGET}/*"
            ]
        }
    ]
}
POLICY_EOF

# Import the custom policy definition into MinIO's global IAM register
mc admin policy create myminio "${BUCKET_TARGET}-policy" "/tmp/${BUCKET_TARGET}-policy.json"

# Provision the new user keypair generated by the host script
mc admin user add myminio "$APP_ACCESS_KEY" "$APP_SECRET_KEY"

# Explicitly bind the dynamic policy to this specific access key mapping
mc admin policy attach myminio "${BUCKET_TARGET}-policy" --user="$APP_ACCESS_KEY"

# Clean up internal temporary workspace traces
rm -f "/tmp/${BUCKET_TARGET}-policy.json"
EOF

# 4. Display the resulting keys to standard output for copy-pasting
echo "===================================================="
echo "🎉 MinIO Scoped Keypair Configured Successfully!"
echo "===================================================="
echo "Bucket Target  : $BUCKET_TARGET"
echo "accessKeyId    : $APP_ACCESS_KEY"
echo "secretAccessKey: $APP_SECRET_KEY"
echo "===================================================="
echo "⚠️  Copy these values immediately. They will not be displayed again."
